title:             Ikram Boukhelif's Blog
subtitle:          Data Science Blog
email:             bk-ikram@hotmail.com
description:       Ikram's Data Science Blog
author:            Ikram Boukhelif
baseurl:           ""
url:               "http://bk-ikram.github.io"
keywords:          blog programming Qatar analytics analysis data machine learning articifial intelligence

# Social Profiles
github_username:   bk-ikram
facebook_username: ikram.boukhelif
linkedin_username: ikram-boukhelif-9965a111b

# Build settings
markdown:          kramdown
highlighter:       rouge
permalink:         pretty
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  
# Analytics
google_analytics:  "UA-108811272-1"
